GET http://localhost:3000/users

###

POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "Nikolas",
  "email": "burk@prisma.io"
}

###

POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "Hello World",
  "authorEmail": "alice@prisma.io"
}

###

PUT http://localhost:3000/post/__OBJECT_ID__/views

###

PUT http://localhost:3000/publish/__OBJECT_ID__

###

GET http://localhost:3000/user/__OBJECT_ID__/drafts

###

GET http://localhost:3000/feed
